version: "3"

services:
  server:
    image: node:18-alpine
    working_dir: /app
    command: node server.js
    volumes:
      - .:/app
    environment:
      - PORT=3000
    deploy:
      replicas: 1

  ngnix:
    image: nginx:latest
    ports:
      - 8080:80
      - 3000:3000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
